basePath: /api/v1
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Form:
    properties:
      consumerno:
        type: integer
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      feeder:
        type: string
      id:
        type: integer
      issueID:
        type: integer
      jobdescription:
        type: string
      location:
        type: string
      nooflabours:
        type: integer
      postno:
        type: string
      section:
        type: string
      substation:
        type: string
      transformer:
        type: string
      typeofjob:
        type: string
      updatedAt:
        type: string
      voltage:
        type: integer
    type: object
  models.Issue:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      desc:
        type: string
      form:
        $ref: '#/definitions/models.Form'
      id:
        type: integer
      post_id:
        type: string
      title:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Provide Info About KSEB Web Server].
  license:
    name: MIT
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: KSEB Web Server
  version: "1.0"
paths:
  /issue:
    get:
      produces:
      - application/json
      responses: {}
      summary: Returns A Single Issue With Post_id
    post:
      consumes:
      - application/json
      parameters:
      - description: Example Request Body
        in: body
        name: reqBody
        required: true
        schema:
          $ref: '#/definitions/models.Issue'
      produces:
      - application/json
      responses: {}
      summary: Create Electricty Issue
  /issue/:id:
    get:
      produces:
      - application/json
      responses: {}
      summary: Returns A Single Issue With id
schemes:
- http
swagger: "2.0"
